---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.8-alpine3.15
  amd64: ghcr.io/home-assistant/amd64-base-python:3.8-alpine3.15
  armhf: ghcr.io/home-assistant/armhf-base-python:3.8-alpine3.15
  armv7: ghcr.io/home-assistant/armv7-base-python:3.8-alpine3.15
  i386: ghcr.io/home-assistant/i386-base-python:3.8-alpine3.15
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  PYESS_VERSION: 0.1.14
