---
version: "1.0.0"
slug: lg_ess
name: "LG ESS"
image: "buktahula/lgess-{arch}"
description: "für Jens ❤️"
url: "https://github.com/Buktahula/hassio-addons/tree/main/LG_ESS"
arch:
  - aarch64
  - amd64
  - armv7
  - i386
host_network: true
homeassistant_api: true
services:
  - mqtt:want
options:
  ess_host: ""
  ess_password: ""
  installer_password: ""
  interval_seconds: 5
  power_unit: "kW"
  entity_naming: "legacy"
  sensor_language: "auto"
  auto_create_sensors: true
  legacy_raw_sensors: true
  mqtt_server: ""
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  hass_autoconfig_sensors: ""
schema:
  ess_host: str?
  ess_password: password?
  installer_password: password?
  interval_seconds: int(1,600)
  power_unit: list(kW|W)?
  entity_naming: list(legacy|modern)?
  sensor_language: list(auto|de|en)?
  auto_create_sensors: bool?
  legacy_raw_sensors: bool?
  mqtt_server: str?
  mqtt_port: int(1,65535)?
  mqtt_user: str?
  mqtt_password: password?
  hass_autoconfig_sensors: str?
startup: services
init: false
