name: "Publish"

on:
  release:
    types: [published]
  push:
    branches:
      - master

env:
  GIT_TAG_NAME: dev

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

  publish:
    name: Publish builder
    needs: init
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        architecture: ${{ fromJson(needs.init.outputs.architectures) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish ${{ matrix.architecture }} builder
        uses: home-assistant/builder@master
        with:
          args: |
            --target /data 
